prod_server:
  host: "localhost"
  # with first slash but no end slash
  http_path: "/"
  trusted_ips: "127.0.0.1,::1i,79.174.228.158,82.228.197.89,46.218.50.230"
  # no first slash
  settings_file: { type: php , path: "config/settings.inc.php" }
  bdd:
    bdd_host: { type: const, name: _DB_SERVER_ }
    # bdd_port: { type: const, name: _DB_SERVER_ }
    bdd_name: { type: const, name: _DB_NAME_ }
    bdd_user: { type: const, name: _DB_USER_ }
    bdd_password: { type: const, name: _DB_PASSWD_ }
  files: [ img, upload ]



